# Generated by Django 4.1.4 on 2022-12-27 13:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addmoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transType', models.CharField(max_length=30)),
                ('quantity', models.BigIntegerField()),
                ('transDate', models.DateField(default=django.utils.timezone.now)),
                ('catData', models.CharField(max_length=50)),
                ('transDisc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('current_balance', models.CharField(max_length=10)),
                ('budget', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TotalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bud', models.CharField(max_length=10)),
            ],
        ),
    ]
