# Generated by Django 4.1.4 on 2022-12-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryList', models.CharField(max_length=50)),
                ('priceList', models.CharField(max_length=100)),
            ],
        ),
    ]
