# Generated by Django 4.1.4 on 2022-12-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0002_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='priceList',
            field=models.IntegerField(max_length=100),
        ),
    ]
