# Generated by Django 4.1.3 on 2022-12-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_alter_expenses_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='priceList',
            field=models.IntegerField(),
        ),
    ]
